# Generated by Django 5.2 on 2025-04-13 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='RUB', max_length=50, unique=True, verbose_name='ISO код валюты')),
                ('symbol', models.CharField(blank=True, default='₽', max_length=10, verbose_name='Символ валюты')),
                ('ticker', models.CharField(blank=True, max_length=50, verbose_name='Тикер вида {ISO}USD=X')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.CreateModel(
            name='CurrencyUSDFixing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currencyFixingDate', models.DateField(blank=True, null=True, verbose_name='Дата валютного фиксинга')),
                ('valueUSD', models.DecimalField(blank=True, decimal_places=20, max_digits=45, null=True, verbose_name='Стоимость в USD')),
                ('currencyId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fixings.currency', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Фиксинг валюты в USD',
                'verbose_name_plural': 'Фиксинги валют в USD',
            },
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indexName', models.CharField(blank=True, max_length=200, unique=True, verbose_name='Имя актива')),
                ('indexISIN', models.CharField(blank=True, max_length=200, verbose_name='ISIN идентификатора актива')),
                ('ccyId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fixings.currency', verbose_name='Код валюты')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.CreateModel(
            name='Fixing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixingDate', models.DateField(blank=True, null=True, verbose_name='Дата фиксинга')),
                ('value', models.DecimalField(blank=True, decimal_places=20, max_digits=45, null=True, verbose_name='Цена закрытия')),
                ('currencyId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fixings.currency', verbose_name='Валюта')),
                ('indexId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fixings.index', verbose_name='Идентификатор бумаги')),
            ],
            options={
                'verbose_name': 'Фиксинг',
                'verbose_name_plural': 'Фиксинги',
            },
        ),
    ]
