# Generated by Django 5.2 on 2025-04-30 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fixings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название портфеля')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Владелец портфеля')),
            ],
            options={
                'verbose_name': 'Портфель акций',
                'verbose_name_plural': 'Портфели акций',
            },
        ),
        migrations.CreateModel(
            name='IndexPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество акции')),
                ('buyDate', models.DateField(verbose_name='Дата покупки')),
                ('initialPrice', models.DecimalField(blank=True, decimal_places=20, max_digits=45, null=True, verbose_name='Цена закупки')),
                ('indexId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fixings.index', verbose_name='Акция')),
                ('portfolioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packets', to='portfolio.portfolio')),
            ],
            options={
                'verbose_name': 'Пакет акции',
                'verbose_name_plural': 'Пакеты акций',
            },
        ),
    ]
