# Generated by Django 5.2 on 2025-05-12 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexpacket',
            name='initialPrice',
        ),
    ]
